version: '3.8'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.5
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://ep-little-sunset-a5eebixq-pooler.us-east-2.aws.neon.tech:5432/database
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=
      - KC_DB_SCHEMA=keycloak
      - KC_TRANSACTION_XA_ENABLED=false
      - KEYCLOAK_USER=user
      - KEYCLOAK_PASSWORD=user
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin

    ports:
      - "9090:8080"
    volumes:
      - ./meu-tema:/opt/keycloak/themes/meu-tema
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev",
      # deactivate theme caching during theme development
              "--spi-theme-static-max-age=-1",
              "--spi-theme-cache-themes=false",
              "--spi-theme-cache-templates=false"
      # ...
    ]
